#========================================================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Automatically Build OpenWrt for Amlogic s9xxx tv box
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
# Source code repository: https://github.com/coolsnowwolf/lede / Branch: master
#========================================================================================================================

name: Build OpenWrt lede ctn..

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_soc:
        description: "Choose Amlogic SoC."
        required: false
        default: "all"
      openwrt_kernel:
        description: "Choose kernel version."
        required: false
        default: "5.15.25_5.10.100"
      openwrt_size:
        description: "Set the rootfs size(Unit: MiB)."
        required: false
        default: "960"
  #schedule:
    #- cron: '0 17 * * 0'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: router-config/lede-master/feeds.conf.default
  CONFIG_FILE: router-config/lede-master/.config
  DIY_P1_SH: router-config/lede-master/diy-part1.sh
  DIY_P2_SH: router-config/lede-master/diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: env.PACKAGED_STATUS == 'success' && !cancelled()
        with:
          tag: openwrt_s9xxx_lede_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is OpenWrt firmware for Amlogic s9xxx tv box
            * Firmware information
            Default IP: 192.168.1.1
            Default username: root
            Default password: password
            Default WIFI name: OpenWrt
            Default WIFI password: none
            Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
